frr defaults traditional
hostname r2
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.2/32
exit
!
interface eth1
 description enlace-r1
 ip address 10.0.12.2/30
exit
!
interface eth2
 description enlace-r5
 ip address 10.0.25.1/30
exit
!
interface eth3
 description lan-h2
 ip address 192.168.2.1/24
exit
!
router bgp 65001
 bgp router-id 10.255.0.2
 no bgp ebgp-requires-policy
 timers bgp 60 180
 neighbor 10.0.12.1 remote-as 65001
 neighbor 10.0.12.1 description iBGP-r1
 neighbor 10.0.12.1 timers connect 10
 neighbor 10.0.25.2 remote-as 65003
 neighbor 10.0.25.2 description eBGP-r5
 neighbor 10.0.25.2 timers connect 10
 !
 address-family ipv4 unicast
  network 10.255.0.2/32
  network 192.168.2.0/24
  neighbor 10.0.12.1 activate
  neighbor 10.0.12.1 next-hop-self
  neighbor 10.0.25.2 activate
 exit-address-family
exit
!
