frr defaults traditional
hostname r2
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.2/32
exit
!
interface eth1
 description enlace-r1
 ip address 10.0.12.2/30
exit
!
interface eth2
 description enlace-r5
 ip address 10.0.25.1/30
exit
!
interface eth3
 description lan-h2
 ip address 192.168.2.1/24
exit
!
router rip
 version 2
 timers basic 30 180 120
 network eth1
 network eth2
 network eth3
 network lo
 passive-interface eth3
 passive-interface lo
exit
!
